namespace :db do
  desc "Fill database with sample data"
  task populate: :environment do
    Client.create!(name: "Inca Plastics Molding Co., Inc.",
                   address: "17129 Koala Rd.\r\nAdelanto, CA 92301\r\nUSA", 
                   phone: "909-923-3235", 
                   website: "http://www.foo.bar",
                   poc_name: "Bill", 
                   poc_title: "Head Honcho", 
                   poc_phone: "", 
                   poc_email: "jim@foo.bar", 
                   invoice_amt: 1500, 
                   invoice_freq: "Annual", 
                   invoice_month: "July", 
                   listing_number: "11K23", 
                   effective: "2014-05-08", 
                   updated: "2014-05-08", 
                   expires: "", 
                   suspended: false, 
                   delisted: false, 
                   comments: "Some stuff here\r\nBut it's long\r\nReally looooong")
    Client.create!(name: "Test Client Bazinga",
                   address: "somewhere\r\nover\r\nthe\r\nrainbow", 
                   phone: "123-456-7890", 
                   website: "http://www.foo2.bar",
                   poc_name: "George", 
                   poc_title: "Pres", 
                   poc_phone: "123-456-7891", 
                   poc_email: "george@foo.bar", 
                   invoice_amt: 4500, 
                   invoice_freq: "Monthly", 
                   invoice_month: "", 
                   listing_number: "10C87", 
                   effective: "2012-05-08", 
                   updated: "2014-05-08", 
                   expires: "2016-03-19", 
                   suspended: false, 
                   delisted: false, 
                   comments: "Some text here")
    Client.create!(name: "Test Client Broccoli",
                   address: "5250 China\r\nDistrict 13\r\nChuangua\r\nChina", 
                   phone: "1-11-098-765-4321", 
                   website: "http://www.foo3.bar",
                   poc_name: "Fred", 
                   poc_title: "Janitor", 
                   poc_phone: "", 
                   poc_email: "fred@foo.bar", 
                   invoice_amt: 25000, 
                   invoice_freq: "Quarterly", 
                   invoice_month: "", 
                   listing_number: "17562", 
                   effective: "2014-05-08", 
                   updated: "2014-05-08", 
                   expires: "2017-05-08", 
                   suspended: false, 
                   delisted: true, 
                   comments: "Texty\r\nTexty\r\nText")
  end
end